---
title: 'Eccezioni: Funzione failwith'
description: Informazioni su come la funzione 'failwith' genera un F# eccezione.
ms.date: 05/16/2016
ms.openlocfilehash: 05d385ddfc98a910779a6f59949a7187c38f0812
ms.sourcegitcommit: fa38fe76abdc8972e37138fcb4dfdb3502ac5394
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/19/2018
ms.locfileid: "53610112"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="b0ed1-103">Eccezioni: Funzione failwith</span><span class="sxs-lookup"><span data-stu-id="b0ed1-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="b0ed1-104">Il `failwith` funzione genera un F# eccezione.</span><span class="sxs-lookup"><span data-stu-id="b0ed1-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="b0ed1-105">Sintassi</span><span class="sxs-lookup"><span data-stu-id="b0ed1-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="b0ed1-106">Note</span><span class="sxs-lookup"><span data-stu-id="b0ed1-106">Remarks</span></span>

<span data-ttu-id="b0ed1-107">Il *stringa di messaggio di errore* nella sintassi precedente è una stringa letterale o un valore di tipo `string`.</span><span class="sxs-lookup"><span data-stu-id="b0ed1-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="b0ed1-108">Diventa il `Message` proprietà dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="b0ed1-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="b0ed1-109">L'eccezione che viene generato dal `failwith` è un `System.Exception` eccezione, ovvero un riferimento con il nome `Failure` in F# codice.</span><span class="sxs-lookup"><span data-stu-id="b0ed1-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="b0ed1-110">Il codice seguente illustra l'uso di `failwith` per generare un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="b0ed1-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="b0ed1-111">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="b0ed1-111">See also</span></span>

- [<span data-ttu-id="b0ed1-112">Gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="b0ed1-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="b0ed1-113">Tipi di eccezione</span><span class="sxs-lookup"><span data-stu-id="b0ed1-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="b0ed1-114">Eccezioni: Il `try...with` espressione</span><span class="sxs-lookup"><span data-stu-id="b0ed1-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="b0ed1-115">Eccezioni: Il `try...finally` espressione</span><span class="sxs-lookup"><span data-stu-id="b0ed1-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="b0ed1-116">Eccezioni: funzione `raise`</span><span class="sxs-lookup"><span data-stu-id="b0ed1-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)