---
title: 'Eccezioni: funzione failwith (F#)'
description: Informazioni su come la funzione 'failwith' genera un'eccezione F#.
ms.date: 05/16/2016
ms.openlocfilehash: 69a2eb69e0157d3bde8cb8884cb0ae960634dddc
ms.sourcegitcommit: db8b83057d052c1f9f249d128b08d4423af0f7c2
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 11/02/2018
ms.locfileid: "43863429"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="4edb5-103">Eccezioni: funzione failwith</span><span class="sxs-lookup"><span data-stu-id="4edb5-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="4edb5-104">Il `failwith` funzione genera un'eccezione F#.</span><span class="sxs-lookup"><span data-stu-id="4edb5-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="4edb5-105">Sintassi</span><span class="sxs-lookup"><span data-stu-id="4edb5-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="4edb5-106">Note</span><span class="sxs-lookup"><span data-stu-id="4edb5-106">Remarks</span></span>

<span data-ttu-id="4edb5-107">Il *stringa di messaggio di errore* nella sintassi precedente è una stringa letterale o un valore di tipo `string`.</span><span class="sxs-lookup"><span data-stu-id="4edb5-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="4edb5-108">Diventa il `Message` proprietà dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="4edb5-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="4edb5-109">L'eccezione che viene generato dal `failwith` è un `System.Exception` eccezione, ovvero un riferimento con il nome `Failure` nel codice F#.</span><span class="sxs-lookup"><span data-stu-id="4edb5-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="4edb5-110">Il codice seguente illustra l'uso di `failwith` per generare un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="4edb5-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="4edb5-111">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="4edb5-111">See also</span></span>

- [<span data-ttu-id="4edb5-112">Gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="4edb5-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="4edb5-113">Tipi di eccezione</span><span class="sxs-lookup"><span data-stu-id="4edb5-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="4edb5-114">Eccezioni: espressione `try...with`</span><span class="sxs-lookup"><span data-stu-id="4edb5-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="4edb5-115">Eccezioni: espressione `try...finally`</span><span class="sxs-lookup"><span data-stu-id="4edb5-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="4edb5-116">Eccezioni: funzione `raise`</span><span class="sxs-lookup"><span data-stu-id="4edb5-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
