---
title: Errore del compilatore CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: f310b4b2b8aa320146d9114a999a82dcae2bb528
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 04/23/2019
ms.locfileid: "61687331"
---
# <a name="compiler-error-cs0156"></a>Errore del compilatore CS0156
L'utilizzo dell'istruzione throw senza argomenti non è consentito in una clausola finally annidata all'interno della clausola catch di inclusione più vicina  
  
 Un'istruzione [throw](../../csharp/language-reference/keywords/throw.md) senza parametri può essere usata solo in una clausola **catch** che non accetta parametri.  
  
 Per altre informazioni, vedere [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md) e [eccezioni e gestione delle eccezioni](../../csharp/programming-guide/exceptions/index.md).  
  
 L'esempio seguente genera l'errore CS0156:  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
