---
title: Errore del compilatore CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 1263fbd4d6591b1f231e38400c680b549ba5654e
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 04/23/2019
ms.locfileid: "61686226"
---
# <a name="compiler-error-cs1626"></a>Errore del compilatore CS1626
Impossibile produrre un valore nel corpo di un blocco try con una clausola catch  
  
 L'istruzione yield non è consentita in un blocco try se è presente una clausola catch associata al blocco try. Per evitare questo errore, spostare l'istruzione yield fuori dal blocco try/catch/finally o rimuovere il blocco catch.
  
 L'esempio seguente genera l'errore CS1626:  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
      finally
      {
      
      }
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
