---
title: "'Catch' non può trovarsi all'esterno di un'istruzione 'Try'"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 71b83937edb7f42c9bd62d6fba998d95bb047115
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/22/2018
ms.locfileid: "53776708"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' non può trovarsi all'esterno di un'istruzione 'Try'
`Catch` deve figurare all'interno di un blocco di istruzioni `Try...Catch...Finally`. Nel blocco `Catch` è presente un'istruzione `Try` non necessaria oppure l'istruzione `Catch` si trova al di fuori dei limiti del blocco `Try` corrispondente.  
  
 **ID errore:** BC30380  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1.  Eliminare l'istruzione `Catch` se non è necessaria oppure inserirla all'interno di un blocco di istruzioni `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
